TEST_IMAGE_ROOT_PATH = 'D:\\pycharmspace\\testimage\\'
TEST_RAW_IMAGE_PATH = TEST_IMAGE_ROOT_PATH + 'raw\\'
TEST_GEOMETRY_IMAGE_PATH = TEST_IMAGE_ROOT_PATH + 'rotated\\'

PASSWORD = '123456'

POOL_LOWER_THRESHOLD = 10
POOL_UPPER_THRESHOLD = 100

CROPED_WIDTH = 511
CROPED_HEIGHT = 383

VALID_CHECK_CYCLE = 60
POOL_LEN_CHECK_CYCLE = 20

TEST_API = 'https://www.baidu.com'